version: "3"
services:
  server:
    container_name: appserver
    image: omenka/fashion-blog
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/week_9

    ports:
      - "8000:8080"
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Decagon@2022
      - POSTGRES_DB=week_9
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
volumes:
  pgdata:
networks:
  default:





