#version: "3"
#services:
#  server:
#    container_name: appserver
#    image: fashionblog
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/week_9
#
#    ports:
#      - "8080:8080"
#    restart: always
#    depends_on:
#      - db
#  db:
#    image: postgres
#    container_name: db
#    environment:
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=Decagon@2022
#      - POSTGRES_DB=week_9
#      - PGDATA=/var/lib/postgresql/data/pgdata
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    restart: always
#  pgadmin:
#    container_name: pgadmin4_container
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"
#volumes:
#  pgdata:
#networks:
#  default:
#
#
#
#
#


version: '3.8'
services:
  API:
    image: fashionblog
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/week_9
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Decagon@2022
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Decagon@2022
      - POSTGRES_DB=week_9
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_is ready -U postgres" ]
      interval: 10s
